# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160926_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
