# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
