# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eulag', '0002_auto_20160810_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='termsheet',
            name='changed_by',
        ),
    ]
